### ISSUE TITLE
请问 ，有办法根据账号密码查询原神是否封号吗？

### ISSUE THREAD

**Issue by loveyeguo** [Dragon-Fish/genshin-kit#3]

**Comment by Dragon-Fish** [comment]
这个的原理是登录米游社，不是登录原神游戏，而且暂时不提供账号密码登录的方法，所以理论上可能无法实现您的需求。

**Comment by loveyeguo** [comment]
我已经实现了如何登陆原神游戏，但是没有分析到有效的字段，所有的用户信息里面，都没有是否封号这个字段。奇怪

**Comment by Dragon-Fish** [comment]
OFF TOPIC

**Comment by Shigma** [comment]
账号密码登录是非法行为，这里不讨论这些内容。
